
services:
  server: 
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes: 
      - ./images:/app/images


    # This is for testing perposes
    ports:
      - 3000:3000
    depends_on:
      - db  